import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import ProviderWithStore from "@/lib/Provider";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar2 from "@/components/navbar/Navbar2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ELYTE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="inter.className">
        <Navbar/>
          <ProviderWithStore>
            {children}
          </ProviderWithStore>
        <Footer/>
      </body>
    </html>
  );
}
